/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMatchesRouteImport } from './routes/_app.matches'
import { Route as AppSettingsRouteRouteImport } from './routes/_app.settings.route'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset.index'
import { Route as PasswordResetConfirmRouteImport } from './routes/password-reset.confirm'
import { Route as AppCrmIndexRouteImport } from './routes/_app.crm.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppStartupsIndexRouteImport } from './routes/_app.startups.index'
import { Route as AppStartupsStartupIdRouteRouteImport } from './routes/_app.startups.$startupId.route'
import { Route as AppCrmApplicationsApplicationIdRouteImport } from './routes/_app.crm.applications.$applicationId'
import { Route as AppStartupsStartupIdIndexRouteImport } from './routes/_app.startups.$startupId.index'
import { Route as AppStartupsStartupIdFoundersRouteImport } from './routes/_app.startups.$startupId.founders'
import { Route as AppStartupsStartupIdJobsRouteImport } from './routes/_app.startups.$startupId.jobs'
import { Route as AppStartupsStartupIdNotesRouteImport } from './routes/_app.startups.$startupId.notes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetConfirmRoute = PasswordResetConfirmRouteImport.update({
  id: '/password-reset/confirm',
  path: '/password-reset/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppStartupsIndexRoute = AppStartupsIndexRouteImport.update({
  id: '/startups/',
  path: '/startups/',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupsStartupIdRouteRoute =
  AppStartupsStartupIdRouteRouteImport.update({
    id: '/startups/$startupId',
    path: '/startups/$startupId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCrmApplicationsApplicationIdRoute =
  AppCrmApplicationsApplicationIdRouteImport.update({
    id: '/crm/applications/$applicationId',
    path: '/crm/applications/$applicationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppStartupsStartupIdIndexRoute =
  AppStartupsStartupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppStartupsStartupIdRouteRoute,
  } as any)
const AppStartupsStartupIdFoundersRoute =
  AppStartupsStartupIdFoundersRouteImport.update({
    id: '/founders',
    path: '/founders',
    getParentRoute: () => AppStartupsStartupIdRouteRoute,
  } as any)
const AppStartupsStartupIdJobsRoute =
  AppStartupsStartupIdJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AppStartupsStartupIdRouteRoute,
  } as any)
const AppStartupsStartupIdNotesRoute =
  AppStartupsStartupIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AppStartupsStartupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/matches': typeof AppMatchesRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/startups/$startupId': typeof AppStartupsStartupIdRouteRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/crm/': typeof AppCrmIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/startups/': typeof AppStartupsIndexRoute
  '/crm/applications/$applicationId': typeof AppCrmApplicationsApplicationIdRoute
  '/startups/$startupId/founders': typeof AppStartupsStartupIdFoundersRoute
  '/startups/$startupId/jobs': typeof AppStartupsStartupIdJobsRoute
  '/startups/$startupId/notes': typeof AppStartupsStartupIdNotesRoute
  '/startups/$startupId/': typeof AppStartupsStartupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/matches': typeof AppMatchesRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset': typeof PasswordResetIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/crm': typeof AppCrmIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/startups': typeof AppStartupsIndexRoute
  '/crm/applications/$applicationId': typeof AppCrmApplicationsApplicationIdRoute
  '/startups/$startupId/founders': typeof AppStartupsStartupIdFoundersRoute
  '/startups/$startupId/jobs': typeof AppStartupsStartupIdJobsRoute
  '/startups/$startupId/notes': typeof AppStartupsStartupIdNotesRoute
  '/startups/$startupId': typeof AppStartupsStartupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/_app/startups/$startupId': typeof AppStartupsStartupIdRouteRouteWithChildren
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/startups/': typeof AppStartupsIndexRoute
  '/_app/crm/applications/$applicationId': typeof AppCrmApplicationsApplicationIdRoute
  '/_app/startups/$startupId/founders': typeof AppStartupsStartupIdFoundersRoute
  '/_app/startups/$startupId/jobs': typeof AppStartupsStartupIdJobsRoute
  '/_app/startups/$startupId/notes': typeof AppStartupsStartupIdNotesRoute
  '/_app/startups/$startupId/': typeof AppStartupsStartupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/matches'
    | '/login'
    | '/register'
    | '/password-reset/confirm'
    | '/password-reset/'
    | '/startups/$startupId'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/profile'
    | '/crm/'
    | '/settings/'
    | '/startups/'
    | '/crm/applications/$applicationId'
    | '/startups/$startupId/founders'
    | '/startups/$startupId/jobs'
    | '/startups/$startupId/notes'
    | '/startups/$startupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/login'
    | '/register'
    | '/password-reset/confirm'
    | '/password-reset'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/profile'
    | '/crm'
    | '/settings'
    | '/startups'
    | '/crm/applications/$applicationId'
    | '/startups/$startupId/founders'
    | '/startups/$startupId/jobs'
    | '/startups/$startupId/notes'
    | '/startups/$startupId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/settings'
    | '/_app/dashboard'
    | '/_app/matches'
    | '/_auth/login'
    | '/_auth/register'
    | '/password-reset/confirm'
    | '/password-reset/'
    | '/_app/startups/$startupId'
    | '/_app/settings/account'
    | '/_app/settings/integrations'
    | '/_app/settings/profile'
    | '/_app/crm/'
    | '/_app/settings/'
    | '/_app/startups/'
    | '/_app/crm/applications/$applicationId'
    | '/_app/startups/$startupId/founders'
    | '/_app/startups/$startupId/jobs'
    | '/_app/startups/$startupId/notes'
    | '/_app/startups/$startupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PasswordResetConfirmRoute: typeof PasswordResetConfirmRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/confirm': {
      id: '/password-reset/confirm'
      path: '/password-reset/confirm'
      fullPath: '/password-reset/confirm'
      preLoaderRoute: typeof PasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/startups/': {
      id: '/_app/startups/'
      path: '/startups'
      fullPath: '/startups/'
      preLoaderRoute: typeof AppStartupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/startups/$startupId': {
      id: '/_app/startups/$startupId'
      path: '/startups/$startupId'
      fullPath: '/startups/$startupId'
      preLoaderRoute: typeof AppStartupsStartupIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/applications/$applicationId': {
      id: '/_app/crm/applications/$applicationId'
      path: '/crm/applications/$applicationId'
      fullPath: '/crm/applications/$applicationId'
      preLoaderRoute: typeof AppCrmApplicationsApplicationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/startups/$startupId/': {
      id: '/_app/startups/$startupId/'
      path: '/'
      fullPath: '/startups/$startupId/'
      preLoaderRoute: typeof AppStartupsStartupIdIndexRouteImport
      parentRoute: typeof AppStartupsStartupIdRouteRoute
    }
    '/_app/startups/$startupId/founders': {
      id: '/_app/startups/$startupId/founders'
      path: '/founders'
      fullPath: '/startups/$startupId/founders'
      preLoaderRoute: typeof AppStartupsStartupIdFoundersRouteImport
      parentRoute: typeof AppStartupsStartupIdRouteRoute
    }
    '/_app/startups/$startupId/jobs': {
      id: '/_app/startups/$startupId/jobs'
      path: '/jobs'
      fullPath: '/startups/$startupId/jobs'
      preLoaderRoute: typeof AppStartupsStartupIdJobsRouteImport
      parentRoute: typeof AppStartupsStartupIdRouteRoute
    }
    '/_app/startups/$startupId/notes': {
      id: '/_app/startups/$startupId/notes'
      path: '/notes'
      fullPath: '/startups/$startupId/notes'
      preLoaderRoute: typeof AppStartupsStartupIdNotesRouteImport
      parentRoute: typeof AppStartupsStartupIdRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppStartupsStartupIdRouteRouteChildren {
  AppStartupsStartupIdFoundersRoute: typeof AppStartupsStartupIdFoundersRoute
  AppStartupsStartupIdJobsRoute: typeof AppStartupsStartupIdJobsRoute
  AppStartupsStartupIdNotesRoute: typeof AppStartupsStartupIdNotesRoute
  AppStartupsStartupIdIndexRoute: typeof AppStartupsStartupIdIndexRoute
}

const AppStartupsStartupIdRouteRouteChildren: AppStartupsStartupIdRouteRouteChildren =
  {
    AppStartupsStartupIdFoundersRoute: AppStartupsStartupIdFoundersRoute,
    AppStartupsStartupIdJobsRoute: AppStartupsStartupIdJobsRoute,
    AppStartupsStartupIdNotesRoute: AppStartupsStartupIdNotesRoute,
    AppStartupsStartupIdIndexRoute: AppStartupsStartupIdIndexRoute,
  }

const AppStartupsStartupIdRouteRouteWithChildren =
  AppStartupsStartupIdRouteRoute._addFileChildren(
    AppStartupsStartupIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppStartupsStartupIdRouteRoute: typeof AppStartupsStartupIdRouteRouteWithChildren
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppStartupsIndexRoute: typeof AppStartupsIndexRoute
  AppCrmApplicationsApplicationIdRoute: typeof AppCrmApplicationsApplicationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppStartupsStartupIdRouteRoute: AppStartupsStartupIdRouteRouteWithChildren,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppStartupsIndexRoute: AppStartupsIndexRoute,
  AppCrmApplicationsApplicationIdRoute: AppCrmApplicationsApplicationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PasswordResetConfirmRoute: PasswordResetConfirmRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
