"""add startups founders jobs saved notes applications notifications enrichment

Revision ID: 1e5deb2dec63
Revises: 0001
Create Date: 2026-08-12 01:51:26.574945+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e5deb2dec63'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('funding_total_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_funding_date', sa.Date(), nullable=True),
    sa.Column('hiring_status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_created_by'), 'startups', ['created_by'], unique=False)
    op.create_index(op.f('ix_startups_hiring_status'), 'startups', ['hiring_status'], unique=False)
    op.create_index(op.f('ix_startups_stage'), 'startups', ['stage'], unique=False)
    op.create_index(
        'uq_startups_website', 'startups', ['website'], unique=True,
        postgresql_where=sa.text('website IS NOT NULL'), sqlite_where=sa.text('website IS NOT NULL'),
    )
    op.create_index('ix_startups_tags_gin', 'startups', ['tags'], postgresql_using='gin')
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrichment_entity', 'enrichment_jobs', ['entity_type', 'entity_id', 'job_type'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_user_id'), 'enrichment_jobs', ['user_id'], unique=False)
    op.create_index('ix_enrichment_status_created', 'enrichment_jobs', ['status', 'created_at'], unique=False)
    op.create_table('founders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('twitter_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('background_summary', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founders_startup_id'), 'founders', ['startup_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('seniority', sa.String(length=40), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_startup_id_status', 'jobs', ['startup_id', 'status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('saved_startups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('saved_via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'startup_id', name='uq_saved_startups_user_startup')
    )
    op.create_index(op.f('ix_saved_startups_startup_id'), 'saved_startups', ['startup_id'], unique=False)
    op.create_index(op.f('ix_saved_startups_user_id'), 'saved_startups', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_startup_id'), 'applications', ['startup_id'], unique=False)
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_index('uq_applications_user_job', 'applications', ['user_id', 'job_id'], unique=True, sqlite_where=sa.text('job_id IS NOT NULL'), postgresql_where=sa.text('job_id IS NOT NULL'))
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('founder_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['founders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_founder_id'), 'notes', ['founder_id'], unique=False)
    op.create_index(op.f('ix_notes_startup_id'), 'notes', ['startup_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_startup_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_founder_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index('uq_applications_user_job', table_name='applications', sqlite_where=sa.text('job_id IS NOT NULL'), postgresql_where=sa.text('job_id IS NOT NULL'))
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_index(op.f('ix_applications_startup_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_saved_startups_user_id'), table_name='saved_startups')
    op.drop_index(op.f('ix_saved_startups_startup_id'), table_name='saved_startups')
    op.drop_table('saved_startups')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_jobs_startup_id_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_founders_startup_id'), table_name='founders')
    op.drop_table('founders')
    op.drop_index('ix_enrichment_status_created', table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_user_id'), table_name='enrichment_jobs')
    op.drop_index('ix_enrichment_entity', table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    op.drop_index(op.f('ix_startups_stage'), table_name='startups')
    op.drop_index(op.f('ix_startups_hiring_status'), table_name='startups')
    op.drop_index(op.f('ix_startups_created_by'), table_name='startups')
    op.drop_index('ix_startups_tags_gin', table_name='startups', postgresql_using='gin')
    op.drop_index(
        'uq_startups_website', table_name='startups',
        postgresql_where=sa.text('website IS NOT NULL'), sqlite_where=sa.text('website IS NOT NULL'),
    )
    op.drop_table('startups')
    # ### end Alembic commands ###
